### ISSUE TITLE
Impossible de mettre à jour l'email d'un utilisateur

### ISSUE THREAD

**Issue by haklop** [haklop/myqapp#33]

**Comment by julienvey** [comment]
Here is the stacktrace : 

```
java.lang.NullPointerException
    at com.infoq.myqapp.service.UserService.update(UserService.java:30)
    at com.infoq.myqapp.controller.UserController.update(UserController.java:38)
    at com.infoq.myqapp.controller.UserController$$FastClassByCGLIB$$f81a6adf.invoke(<generated>)
```

No error is raised on the web side
